export const COLORS = {
  void: "#030308",
  bg: "#08081a",
  surface1: "#10102a",
  surface2: "#181840",
  surface3: "#222255",
  gold: "#F5C542",
  goldSoft: "#F5C54220",
  goldGlow: "#F5C54240",
  electric: "#818CF8",
  cyan: "#22D3EE",
  white: "#F5F0E8",
  gray1: "#A8A3B3",
  gray2: "#5C576B",
  gray3: "#2E2A3B",
  success: "#34D399",
  warning: "#FBBF24",
  danger: "#FB7185",
};

export const FONTS = {
  primary: "System",
  display: "System",
  accent: "System",
};

export const DEITIES = [
  { id: 1, name: "Zorath", color: "#FF6B35", glow: "#FF6B3540", stoneColor: "#2a1a12", symbolDesc: "flame" },
  { id: 2, name: "Kaelis", color: "#4E9AF1", glow: "#4E9AF140", stoneColor: "#141c26", symbolDesc: "eye" },
  { id: 3, name: "Tharun", color: "#45B764", glow: "#45B76440", stoneColor: "#1e1e14", symbolDesc: "tree" },
  { id: 4, name: "Vynel", color: "#C8D0DB", glow: "#C8D0DB40", stoneColor: "#22262a", symbolDesc: "spiral" },
  { id: 5, name: "Aethis", color: "#A855F7", glow: "#A855F740", stoneColor: "#0e0a14", symbolDesc: "star" },
  { id: 6, name: "Solmara", color: "#FACC15", glow: "#FACC1540", stoneColor: "#2a2416", symbolDesc: "sun" },
  { id: 7, name: "Luneth", color: "#93C5FD", glow: "#93C5FD40", stoneColor: "#18202a", symbolDesc: "moon" },
];

export const GOAL_CATEGORIES = [
  { key: "money", emoji: "💰", label: "Money" },
  { key: "health", emoji: "💪", label: "Health" },
  { key: "relationship", emoji: "❤️", label: "Love" },
  { key: "career", emoji: "📈", label: "Career" },
  { key: "education", emoji: "📚", label: "Education" },
  { key: "family", emoji: "🏠", label: "Family" },
  { key: "spiritual", emoji: "🧘", label: "Spiritual" },
  { key: "travel", emoji: "✈️", label: "Travel" },
  { key: "creativity", emoji: "🎨", label: "Creativity" },
  { key: "fame", emoji: "⭐", label: "Fame" },
  { key: "peace", emoji: "🕊️", label: "Peace" },
  { key: "confidence", emoji: "🦁", label: "Confidence" },
  // Added from the expanded category set
  { key: "happiness", emoji: "😊", label: "Happiness" },
  { key: "success", emoji: "🏆", label: "Success" },
  { key: "wisdom", emoji: "🦉", label: "Wisdom" },
  { key: "gratitude", emoji: "🌟", label: "Gratitude" },
  { key: "fitness", emoji: "🏋️", label: "Fitness" },
  { key: "beauty", emoji: "🌸", label: "Beauty" },
  { key: "friendship", emoji: "🤝", label: "Friendship" },
  { key: "abundance", emoji: "🌈", label: "Abundance" },
  { key: "self_love", emoji: "🪞", label: "Self Love" },
  { key: "courage", emoji: "🦁", label: "Courage" },
  { key: "patience", emoji: "🕊️", label: "Patience" },
  { key: "discipline", emoji: "🎯", label: "Discipline" },
  { key: "forgiveness", emoji: "🤍", label: "Forgiveness" },
  { key: "purpose", emoji: "🧭", label: "Purpose" },
  { key: "leadership", emoji: "👑", label: "Leadership" },
  { key: "harmony", emoji: "☯️", label: "Harmony" },
  { key: "protection", emoji: "🛡️", label: "Protection" },
  { key: "focus", emoji: "🔍", label: "Focus" },
  { key: "joy", emoji: "🎉", label: "Joy" },
  { key: "healing", emoji: "🌿", label: "Healing" },
  { key: "prosperity", emoji: "💎", label: "Prosperity" },
  { key: "inner_strength", emoji: "⚡", label: "Inner Strength" },
  { key: "positivity", emoji: "☀️", label: "Positivity" },
  { key: "custom", emoji: "✏️", label: "Custom" },
];

export const SACRIFICE_CATEGORIES = [
  { key: "social_media", emoji: "📱", label: "Social Media" },
  { key: "entertainment", emoji: "🎮", label: "Entertainment" },
  { key: "shopping", emoji: "🛒", label: "Shopping" },
  { key: "junk_food", emoji: "🍔", label: "Junk Food" },
  { key: "oversleeping", emoji: "😴", label: "Oversleeping" },
  { key: "gossip", emoji: "🗣️", label: "Gossip" },
  { key: "procrastination", emoji: "⏰", label: "Procrastination" },
  { key: "alcohol", emoji: "🍷", label: "Alcohol" },
  { key: "laziness", emoji: "🛋️", label: "Laziness" },
  { key: "negativity", emoji: "😤", label: "Negativity" },
  { key: "toxic_relations", emoji: "💔", label: "Toxic Relations" },
  { key: "overthinking", emoji: "🧠", label: "Overthinking" },
  // Added from the expanded category set
  { key: "smoking", emoji: "🚬", label: "Smoking" },
  { key: "complaining", emoji: "😤", label: "Complaining" },
  { key: "jealousy", emoji: "😒", label: "Jealousy" },
  { key: "anger", emoji: "😡", label: "Anger" },
  { key: "excuses", emoji: "🙈", label: "Excuses" },
  { key: "self_doubt", emoji: "❓", label: "Self Doubt" },
  { key: "comparing", emoji: "⚖️", label: "Comparing" },
  { key: "screen_time", emoji: "🖥️", label: "Screen Time" },
  { key: "sugar", emoji: "🍬", label: "Sugar" },
  { key: "late_nights", emoji: "🌙", label: "Late Nights" },
  { key: "impulse_buying", emoji: "💳", label: "Impulse Buying" },
  { key: "binge_watching", emoji: "📺", label: "Binge Watching" },
  { key: "people_pleasing", emoji: "😅", label: "People Pleasing" },
  { key: "perfectionism", emoji: "🔄", label: "Perfectionism" },
  { key: "mindless_scrolling", emoji: "👆", label: "Mindless Scrolling" },
  { key: "fast_food", emoji: "🍟", label: "Fast Food" },
  { key: "caffeine", emoji: "☕", label: "Caffeine" },
  { key: "revenge", emoji: "😈", label: "Revenge" },
  { key: "gambling", emoji: "🎰", label: "Gambling" },
  { key: "lying", emoji: "🤥", label: "Lying" },
  { key: "drugs", emoji: "💊", label: "Drugs" },
  { key: "porn", emoji: "🔞", label: "Porn" },
  { key: "toxic_music", emoji: "🎵", label: "Toxic Music" },
  { key: "road_rage", emoji: "🚗", label: "Road Rage" },
  { key: "custom", emoji: "✏️", label: "Custom" },
];

export const CYCLE_OPTIONS = [
  { days: 7, label: "7 Days", desc: "A gentle start" },
  { days: 21, label: "21 Days", desc: "Habit-forming cycle" },
  { days: 40, label: "40 Days", desc: "Sacred discipline" },
  { days: 90, label: "90 Days", desc: "Deep transformation" },
];

// Reminder frequency options offered in Settings and Manifest Setup (max 10/day).
export const REMINDER_OPTIONS = [0, 1, 2, 3, 5, 7, 10];

// English + the 22 official (Scheduled) Indian languages + major global languages,
// selectable for daily affirmations. For now ONLY English affirmation content exists —
// the backend always serves English text regardless of the language chosen here (see
// AFFIRMATIONS in server.py) — the user's preference is still saved so translated content
// can be switched on for any of these languages in a future update without any app changes.
export const LANGUAGES = [
  { code: "english", label: "English" },
  { code: "hindi", label: "हिन्दी · Hindi" },
  // All Global Languages
  { code: "spanish", label: "Español · Spanish" },
  { code: "french", label: "Français · French" },
  { code: "german", label: "Deutsch · German" },
  { code: "portuguese", label: "Português · Portuguese" },
  { code: "italian", label: "Italiano · Italian" },
  { code: "dutch", label: "Nederlands · Dutch" },
  { code: "russian", label: "Русский · Russian" },
  { code: "ukrainian", label: "Українська · Ukrainian" },
  { code: "polish", label: "Polski · Polish" },
  { code: "turkish", label: "Türkçe · Turkish" },
  { code: "arabic", label: "العربية · Arabic" },
  { code: "persian", label: "فارسی · Persian" },
  { code: "hebrew", label: "עברית · Hebrew" },
  { code: "chinese", label: "中文 · Chinese" },
  { code: "japanese", label: "日本語 · Japanese" },
  { code: "korean", label: "한국어 · Korean" },
  { code: "thai", label: "ไทย · Thai" },
  { code: "vietnamese", label: "Tiếng Việt · Vietnamese" },
  { code: "indonesian", label: "Bahasa Indonesia · Indonesian" },
  { code: "malay", label: "Bahasa Melayu · Malay" },
  { code: "filipino", label: "Filipino" },
  { code: "swahili", label: "Kiswahili · Swahili" },
  { code: "greek", label: "Ελληνικά · Greek" },
  { code: "swedish", label: "Svenska · Swedish" },
  { code: "norwegian", label: "Norsk · Norwegian" },
  { code: "danish", label: "Dansk · Danish" },
  { code: "finnish", label: "Suomi · Finnish" },
  { code: "czech", label: "Čeština · Czech" },
  { code: "romanian", label: "Română · Romanian" },
  { code: "hungarian", label: "Magyar · Hungarian" },
  // All Regional / Indian Languages (Hindi already listed above)
  { code: "assamese", label: "অসমীয়া · Assamese" },
  { code: "bengali", label: "বাংলা · Bengali" },
  { code: "bodo", label: "बड़ो · Bodo" },
  { code: "dogri", label: "डोगरी · Dogri" },
  { code: "gujarati", label: "ગુજરાતી · Gujarati" },
  { code: "kannada", label: "ಕನ್ನಡ · Kannada" },
  { code: "kashmiri", label: "کٲشُر · Kashmiri" },
  { code: "konkani", label: "कोंकणी · Konkani" },
  { code: "maithili", label: "मैथिली · Maithili" },
  { code: "malayalam", label: "മലയാളം · Malayalam" },
  { code: "manipuri", label: "মৈতৈলোন্ · Manipuri (Meitei)" },
  { code: "marathi", label: "मराठी · Marathi" },
  { code: "nepali", label: "नेपाली · Nepali" },
  { code: "odia", label: "ଓଡ଼ିଆ · Odia" },
  { code: "punjabi", label: "ਪੰਜਾਬੀ · Punjabi" },
  { code: "sanskrit", label: "संस्कृतम् · Sanskrit" },
  { code: "santali", label: "ᱥᱟᱱᱛᱟᱲᱤ · Santali" },
  { code: "sindhi", label: "سنڌي · Sindhi" },
  { code: "tamil", label: "தமிழ் · Tamil" },
  { code: "telugu", label: "తెలుగు · Telugu" },
  { code: "urdu", label: "اردو · Urdu" },
];

export const PRICING = [
  { plan: "first_month", price: 29, per: null, badge: "🌱 Seeker", label: "First Month" },
  { plan: "monthly", price: 49, per: 49, badge: "⚡ Practitioner", label: "Monthly" },
  { plan: "6_month", price: 249, per: 41.5, badge: "🔥 Devoted", label: "6 Months" },
  { plan: "yearly", price: 399, per: 33.3, badge: "👑 Enlightened", label: "Yearly" },
];

export * from "./currency";
